### ISSUE TITLE
scCODA convergence issue for continous covairables

### ISSUE THREAD

**Issue by Marwansha** [scverse/pertpy#597]
Hey,
I'm experiencing issues with scCODA when analyzing the effect of a continuous covariate (like age  for ex ) as opposed to a categorical ones .  using continuous values yields nonsensical results, showing a credible effect on all cell types and by looking at the extended summary(below) the high-density interval for each parameter has zero width (Markov chain getting stuck.??)

<img width="1183" alt="image" src="https://github.com/theislab/pertpy/assets/144441199/071001a0-60f8-4d2e-a5a4-7041fe564322">

while results from using age as categorical with CODA , or comparing with linear regression while using age as categorical or  continous age covariate,  all the output from those match perfectly (scCODA categorical ,or lm continour or categorical ). its just using any continuous covariate in scCODA , i tried differnt covarites too and still same issue when its continous.

I don't mind sharing the data too by email if you would like

Thanks a lot in advance

### Version information

-----
anndata             0.10.5.post1
cell2cell           0.7.3
decoupler           1.6.0
matplotlib          3.8.3
numpy               1.26.4
pandas              2.2.1
pertpy              0.6.0
plotnine            0.13.0
pydeseq2            0.4.7
scanpy              1.9.8
scikit_posthocs     0.9.0
seaborn             0.13.2
session_info        1.0.0
-----
Python 3.9.18 (main, Aug 28 2023, 06:39:39) [GCC 9.2.0]
Linux-4.18.0-477.43.1.el8_8.x86_64-x86_64-with-glibc2.28
-----
Session information updated at 2024-05-16 17:58

**Comment by johannesostner** [comment]
As already discussed in the original scCODA repo (https://github.com/theislab/scCODA/issues/96), I think this is either an issue with data types/covariate normalization or a bug in the code.
Unfortunately, I don't have the time atm to take an extended look at this. Could maybe someone else take this over?

**Comment by Zethson** [comment]
@johannesostner can't make promises yet, but maybe after the preprint I have a few people that can have a stab at this. I'll put it into our backlog.

**Comment by Marwansha** [comment]
hi , i was wondering if there is any updates on this?

i shared couple of month ago the data  but never got any answer back.

**Comment by Zethson** [comment]
We're looking into this. Please remain patient.

**Comment by Marwansha** [comment]
Thanks!

have a nice day

**Comment by Zethson** [comment]
@Marwansha whom did you sent the data again? @Lilly-May would look into this now but would need the dataset ideally, please.

**Comment by Marwansha** [comment]
Hi, she can send me by email and I will share it

Thanks

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Lilly-May** [comment]
Hi @Marwansha!
As discussed via email, I’ve looked into your issue. I was able to reproduce it using your data. However, the problem was resolved for me when I normalized the continuous covariate.

For example, I tested this with age. As you mentioned, using age groups as covariate works, but using age as a continuous covariate directly does not. However, applying simple min-max normalization resolved the issue. You can see this in the [notebook here](https://github.com/Lilly-May/data-processing-pertpy/blob/main/scCODA_continuous_covariate.ipynb).

If you have time, please check if normalizing the features resolves the problem for you as well and report back here. I’m happy to look into this further if you’re still facing issues.

**Comment by Marwansha** [comment]
Hi,

Thanks alot for taking the time to check this,

I checked the notebook and I understood the issue, I will try to reproduce it and let you know if it work.


I just have 1 question to confirm I understand exactly.

1)The normalisation step is  only needed for continuous variables? Since the model worked just fine for the categorical values   when ran on raw counts.?


2) doesn't scCODA do a step of normalisation of the counts?

Thanks alot tho,  will let you know soon

Best
Marwan


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by johannesostner** [comment]
Hi @Marwansha !

I'm glad that there was finally a solution to your problem. Just to make it clear again - we are talking about normalizing covariates - i.e. the values of the columns in your `anndata.obs` that you specify in the formula, not the counts in `anndata.X`.

To answer your questions:
- Yes, you only need to normalize continuous covariates. Like in a linear regression model, all your covariates should be on a similar scale, which is close to [0, 1]. For categorical covariates, this is automatically the case since they are encoded in a binary fashion. For continuous ones, you need to do this yourself. As @Lilly-May stated, min-max scaling to the interval [0, 1] has shown good results in all our experiments so far.
- No, the counts do not need to be normalized, since scCODA is a compositional model and therefore models proportions between cell types. For them, the total count per sample is irrelevant.
